version: '3.8'
services:
  tirgo-merchant-ui:
    container_name: tirgo-merchant-ui
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      - NGINX_PORT=4300
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./dist/tirgo-merchant:/var/www/merchant.tirgo.io
