version: '3.8'
services:
  merchant-ui:
    container_name: tirgo-merchant
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "6061:6061"
    environment:
      - NGINX_PORT=6061
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./dist/tirgo-merchant:/var/www/merchant.tirgo.io
